const styles = {
  textHome: { display: "flex", flexDirection: "column", ml: { xs: 0, md: 10 } },
  searchHome: {
    display: "flex",
    my: 8,
    mx: "auto",
    width: { xs: "100%", md: "30%" },
  },
  mapImage: {
    width: "100%",
    height: "auto",
    objectFit: "fill",
    py: { xs: 0, sm: 5 },
    px: { xs: 0, sm: 7 },
  },
  locationsHome: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    justifyContent: { xs: "center", md: "space-between" },
    alignItems: { xs: "center", md: "flex-start" },
    px: { xs: 0, sm: 7.5 },
    mt: 8,
  },
  secondaryHome: {
    width: { xs: "80%", sm: "25%", lg: "15%" },
    borderRadius: 4,
    border: 3,
    mt: { xs: 2, md: 0 },
  },
  mapHome: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    width: "100%",
    px: { xs: 1, md: 7 },
    pt: 8,
    gap: 4,
  },
  mapText: {
    display: "flex",
    flexDirection: "column",
    width: { xs: "100", md: "50%" },
    justifyContent: "space-evenly",
  },
  secondaryMap: {
    width: { xs: "80%", sm: "40%", lg: "25%" },
    borderRadius: 4,
    border: 3,
    mt: { xs: 2, sm: 0 },
    mx: { xs: "auto", md: 0 },
  },
  mapLegend: {
    width: { xs: "100", md: "50%" },
    height: "auto",
    borderRadius: 10,
  },
  textColumnBox: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    width: "100%",
    justifyContent: "space-evenly",
    mt: { xs: 5, md: 10 },
    alignItems: "center",
    gap: 5,
  },
  imageMiddle: {
    width: { xs: "250px", md: "400px" },
    height: "auto",
    borderRadius: 10,
  },
  contactFormBox: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    width: "100%",
    mt: { xs: 8, md: 15 },
    mb: 8,
    justifyContent: "space-evenly",
    alignItems: "center",
    gap: 8,
  },
  imageForm: {
    width: { xs: "300px", md: "600px" },
    height: "auto",
    borderRadius: 10,
    order: { xs: 1, md: 2 },
  },
};

export default styles;
