export const styles = {
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    px: 3,
    py: { xs: 1, sm: 2 },
  },
  riznica: {
    flexGrow: 1,
    minWidth: 0,
    textAlign: "left",
    fontWeight: "bold",
    color: "black",
  },
  menu: {
    flexGrow: 2,
    minWidth: 0,
    display: { xs: "none", md: "flex" },
    justifyContent: "center",
    gap: 4,
    "@media (max-width:1024px)": {
      gap: 2,
      "& > *": {
        px: 1.5,
      },
    },
    "@media (max-width:768px)": {
      gap: 1,
      "& > *": {
        px: 1,
        fontSize: "0.8rem",
      },
    },
  },
  login: {
    flexGrow: 1,
    minWidth: 0,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  socialMedia: {
    color: "#fff",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
    transition: "all 0.3s ease",
    mx: 1,
    mb: {
      xs: 1,
      sm: 0,
    },
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      transform: "scale(1.1)",
    },
    justifyContent: { xs: "center", sm: "flex-start" },
  },
  footer: {
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1300,
    px: 4,
    py: 2,
    backgroundColor: "#B12C00",
    borderRadius: "30px 30px 0 0",
    boxShadow: "0px -4px 20px rgba(0,0,0,0.1)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    color: "white",
    flexDirection: { xs: "column", sm: "row" },
  },
  navbar: {
    borderRadius: "0 0 30px 30px",
    px: 1,
    backgroundColor: "white",
    position: "sticky",
  },
  banner: {
    width: "100%",
    px: {
      xs: 4,
      sm: 8,
    },
    py: {
      xs: 3,
      sm: 6,
    },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    gap: {
      xs: 2,
      sm: 20,
    },
    flexDirection: {
      xs: "column",
      sm: "row",
    },
    textAlign: {
      xs: "center",
      sm: "left",
    },
  },
  list: {
    display: "flex",
    flexDirection: "column",
    px: 10,
  },
  menuIcon: {
    display: { xs: "block", md: "none" },
    position: "absolute",
    right: 16,
  },
  primaryInBanner: {
    width: {
      xs: "50%",
      sm: "20%",
    },
    borderRadius: 4,
    py: 1,
  },
  primaryInNavbar: {
    display: { xs: "none", md: "flex" },
    width: "100px",
    borderRadius: "1rem",
    py: 1,
    px: 3,
  },
  drawer: {
    backgroundColor: "white",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    py: 2,
  },
};
