export const styles = {
  riznica: {
    flexBasis: "20%",
    textAlign: "left",
    fontWeight: "bold",
    color: "black",
  },
  menu: {
    flexGrow: 1,
    display: "flex",
    justifyContent: "center",
    gap: 4,
  },
  login: {
    flexBasis: "20%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  socialMedia: {
    color: "#fff",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: "50%",
    transition: "all 0.3s ease",
    mx: 1,
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.3)",
      transform: "scale(1.1)",
    },
  },
  footer: {
    position: "sticky",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1300,
    px: 4,
    py: 2,
    backgroundColor: "#B12C00",
    borderRadius: "30px 30px 0 0",
    boxShadow: "0px -4px 20px rgba(0,0,0,0.1)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    color: "white",
  },
  navbar: {
    borderRadius: "0 0 30px 30px",
    px: 1,
    backgroundColor: "white",
    position: "sticky",
  },
  banner: {
    width: "100%",
    px: 8,
    py: 6,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 20,
  },
};
