const styles = {
  row: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    justifyContent: "space-evenly",
    width: "100%",
    my: { xs: 10, md: 15 },
    gap: { xs: 6, md: 10 },
  },
  column: {
    display: "flex",
    flexDirection: "column",
    width: { xs: "100%", md: "35%" },
    mx: { xs: "auto", md: 0 },
  },
  text: (reverse) => ({
    display: "flex",
    flexDirection: "column",
    width: { xs: "80%", md: "20%" },
    justifyContent: "space-evenly",
    alignItems: { xs: "center", md: reverse ? "flex-end" : "flex-start" },
    textAlign: { xs: "center", md: reverse ? "right" : "left" },
    mx: { xs: "auto", md: 0 },
    order: { xs: 1, md: reverse ? 2 : 1 },
    gap: 1,
  }),
  button: {
    width: { xs: "80%", md: "70%" },
    borderRadius: 4,
    border: 3,
    mt: { xs: 3, md: 10 },
  },
  photo: (reverse) => ({
    width: { xs: "250px", sm: "300px", lg: "400px" },
    height: "auto",
    borderRadius: 10,
    mx: { xs: "auto", md: 0 },
    order: { xs: 1, md: reverse ? 1 : 2 },
  }),
  text2: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    mt: 2,
    textAlign: { xs: "center", md: "right" },
    alignItems: { xs: "center", md: "flex-start" },
  },
  button2: {
    width: { xs: "60%", md: "50%" },
    borderRadius: 4,
    border: 3,
    mt: 6,
  },
  photo2: {
    width: { xs: "250px", sm: "300px", lg: "350px" },
    height: "auto",
    borderRadius: 10,
    mx: { xs: "auto", md: 0 },
  },
  text3: {
    display: "flex",
    flexDirection: "column",
    width: { xs: "90%", md: "80%" },
    alignItems: { xs: "center", md: "flex-end" },
    textAlign: { xs: "center", md: "right" },
    mx: "auto",
    gap: 1,
  },

  photo3: {
    width: { xs: "250px", sm: "300px", lg: "350px" },
    height: "auto",
    borderRadius: 10,
    mx: { xs: "auto", md: 0 },
  },
  twoLittle: {
    display: "flex",
    flexDirection: "column",
    width: { xs: "100%", md: "50%" },
    justifyContent: "space-between",
    mx: { xs: "auto", md: 0 },
    gap: 4,
  },
  redBox: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "info.main",
    color: "white",
    p: 4,
    borderRadius: 8,
    gap: 2,
    width: "35%",
  },
};
export default styles;
